### ISSUE TITLE
DockerでVOICEVOX（音声合成）を動かす

### ISSUE THREAD

**Issue by ancient-blog** [ancient-blog/hugo.github.io#17]
[ここ](https://zenn.dev/isi00141/articles/54c5c176f6ac1a)を参照

**Comment by ancient-blog** [comment]
[dockerコンテナを動かす方法](https://qiita.com/suzuki0430/items/d625f8b57ae317ae7d66)を参照

``` yaml
name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: #起動するコンテナイメージを指定
      image:  voicevox/voicevox_engine:cpu-ubuntu20.04-latest #指定のdockerイメージを使用
    steps: #dockerコンテナ内でステップを実行
      - name: Log node version
        run: |
          node -v #nodeバージョンの確認
          cat /etc/os-release #Linuxバージョンの確認
```
